### ISSUE TITLE
esphome flasher not working with ESP32 S3 

### ISSUE THREAD

**Issue by mastrumisciu** [esphome/esphome-flasher#206]
Hi do you know if there is any compatibility issue with ESP S3 devkit 1 ? I can upload bin files to ESP32 room but when I try the same with S3 I get the following message:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/esphomeflasher/common.py", line 194, in detect_chip
    chip = esptool.ESPLoader.detect_chip(port)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/esptool.py", line 288, in detect_chip
    raise FatalError("Unexpected UART datecode value 0x%08x. Failed to autodetect chip type." % date_reg)
esptool.FatalError: Unexpected UART datecode value 0x03700000. Failed to autodetect chip type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/esphomeflasher/gui.py", line 163, in run
    run_esphomeflasher(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/esphomeflasher/__main__.py", line 95, in run_esphomeflasher
    chip = detect_chip(port, args.esp8266, args.esp32)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/esphomeflasher/common.py", line 196, in detect_chip
    raise EsphomeflasherError("ESP Chip Auto-Detection failed: {}".format(err))
esphomeflasher.common.EsphomeflasherError: ESP Chip Auto-Detection failed: Unexpected UART datecode value 0x03700000. Failed to autodetect chip type.

**Comment by Frtrillo** [comment]
bump
mine flash it but with wrong binaries most likely, i get header errors.
