### ISSUE TITLE
Failing to flash esp8266 nodemcu

### ISSUE THREAD

**Issue by jbrown8380** [esphome/esphome-flasher#225]
I'm using Fedora 37 with python 3.11.  I've confirmed that the device is present at /dev/ttyUSB0.  I'm seeing the following errors:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/esphomeflasher/gui.py", line 170, in run
    run_esphomeflasher(argv)
  File "/usr/lib/python3.11/site-packages/esphomeflasher/__main__.py", line 115, in run_esphomeflasher
    chip = detect_chip(port, args.esp8266, args.esp32)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/esphomeflasher/common.py", line 221, in detect_chip
    chip = esptool.ESPLoader.detect_chip(port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ESPLoader' has no attribute 'detect_chip'

Any help would be appreciated.

**Comment by jbrown8380** [comment]
Additional details: I'm using version 1.4.0 of the esphome-flasher.
