### ISSUE TITLE
 esphome-flasher fails running under MacOS X Big Sur  11.2.1

### ISSUE THREAD

**Issue by wojciechczyz** [esphome/esphome-flasher#49]
installed with pip3 under python 3.9.0b5

Traceback (most recent call last):
  File "/Users/w/.pyenv/versions/3.9.0b5/bin/esphomeflasher", line 5, in <module>
    from esphomeflasher.__main__ import main
  File "/Users/w/.pyenv/versions/3.9.0b5/lib/python3.9/site-packages/esphomeflasher/__main__.py", line 8, in <module>
    import esptool
  File "/Users/w/.pyenv/versions/3.9.0b5/bin/esptool.py", line 57, in <module>
    import serial.tools.list_ports as list_ports
  File "/Users/w/.pyenv/versions/3.9.0b5/lib/python3.9/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/w/.pyenv/versions/3.9.0b5/lib/python3.9/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/w/.pyenv/versions/3.9.0b5/lib/python3.9/site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found

**Comment by lightheaded** [comment]
I managed to fix the very same error by running
```pip3 install pyserial --upgrade```

Thanks, @OttoWinter!
